name: Build iOS .ipa file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on macOS environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g @ionic/cli
        npm install

    - name: Build the Ionic project
      run: |
        ionic build --prod
        npx cap sync ios

    - name: Set up CocoaPods (iOS dependencies)
      run: |
        cd ios/App
        pod install

    - name: Build the iOS .ipa file
      run: |
        cd ios
        xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive

    - name: Export .ipa file
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist $PWD/ExportOptions.plist -exportPath $PWD/build/ipa

    - name: Upload .ipa as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa
        path: ios/build/ipa/*.ipa
